first commit of authentication
Gupta-Shivanee/E-commerce pull request #1
Opened 2021-03-12 12:20 UTC by Gupta-Shivanee

trello URL :
https://trello.com/c/0bztVmAD/10-e-commerce-website-authentication-flow

UI Screenshots:

![Screenshot from 2021-03-12 17-07-37](https://user-images.githubusercontent.com/79202689/110938993-b8767b80-835a-11eb-95fe-e347e425053f.png)
![Screenshot from 2021-03-12 17-07-42](https://user-images.githubusercontent.com/79202689/110938996-b90f1200-835a-11eb-927f-f9b9b2a9ccad.png)
![Screenshot from 2021-03-12 17-07-48](https://user-images.githubusercontent.com/79202689/110938997-b9a7a880-835a-11eb-96c5-53cc4352a57a.png)
![Screenshot from 2021-03-12 17-08-01](https://user-images.githubusercontent.com/79202689/110938999-ba403f00-835a-11eb-83c3-9b082fa7d4a7.png)

2021-03-13 13:57 UTC, kalpana19sharma requested changes

2021-03-13 13:57 UTC, kalpana19sharma commented on app/controllers/application_controller.rb
> +  helper_method :logged_in?
Combine these lines of code.

2021-03-13 13:57 UTC, kalpana19sharma commented on app/controllers/application_controller.rb
> +    User.find_by(id: session[:user_id])
This will fire database queries each time this method is called even in a single request. Try to minimize the database queries.

2021-03-13 13:57 UTC, kalpana19sharma commented on app/controllers/application_controller.rb
> +    !current_user.nil?
Use `.present?` instead of checking `nil?` and reverting the condition.

2021-03-13 13:57 UTC, kalpana19sharma commented on app/controllers/application_controller.rb
> +  def authorized
Rename this method to `authenticate_user!`

2021-03-13 13:57 UTC, kalpana19sharma commented on app/controllers/sessions_controller.rb
> +  end
Use single line syntax for empty method
```suggestion
  def new; end
```

2021-03-13 13:57 UTC, kalpana19sharma commented on app/controllers/sessions_controller.rb
> +      redirect_to '/welcome_user'
Use routes helper

2021-03-13 13:57 UTC, kalpana19sharma commented on app/controllers/sessions_controller.rb
> +    if user&.authenticate(params[:password])
Use strong parameters

2021-03-13 13:57 UTC, kalpana19sharma commented on app/controllers/sessions_controller.rb
> +  end
this should not be in this controller

2021-03-13 13:57 UTC, kalpana19sharma commented on app/controllers/sessions_controller.rb
> +  end
What's this for?

2021-03-13 13:57 UTC, kalpana19sharma commented on app/controllers/sessions_controller.rb
> +    redirect_to root_url
Set a flash message for successful logout.

2021-03-13 13:57 UTC, kalpana19sharma commented on app/controllers/users_controller.rb
> +  end
Fix indentation

2021-03-13 13:57 UTC, kalpana19sharma commented on app/controllers/users_controller.rb
> +    @user = User.create(params.require(:user).permit(:full_name, :email, :password, :gender, :mobile_no))
extract `params.require(:user).permit(:full_name, :email, :password, :gender, :mobile_no)` logic in separate method.

2021-03-13 13:57 UTC, kalpana19sharma commented on app/controllers/users_controller.rb
> +    @user = User.create(params.require(:user).permit(:full_name, :email, :password, :gender, :mobile_no))
What if any validation fails?

2021-03-13 13:57 UTC, kalpana19sharma commented on app/models/user.rb
> +  validates :mobile_no, presence: true,numericality: true, length: { is: 10}
Use proper spaces

2021-03-13 13:57 UTC, kalpana19sharma commented on app/views/sessions/new.html.erb
> +  <%= text_field_tag :email%>
Use `email_field` and use proper spaces

2021-03-13 13:57 UTC, kalpana19sharma commented on app/views/sessions/new.html.erb
> +<%= form_tag '/login' do %>
Use routes helper

2021-03-13 13:57 UTC, kalpana19sharma commented on app/views/sessions/new.html.erb
> +<%end%>
Use proper spaces

2021-03-13 13:57 UTC, kalpana19sharma commented on app/views/sessions/welcome.html.erb
> +<%= button_to "Sign Up", '/users/new', method: :get%>
Use routes helper

2021-03-13 13:57 UTC, kalpana19sharma commented on app/views/sessions/welcome_user.html.erb
> +  <%= "Logged in as #{current_user.email}" %> | <%= link_to 'Logout', root_path, method: :get %>
No need to explicitly specify get method

2021-03-13 13:57 UTC, kalpana19sharma commented on app/views/users/new.html.erb
> +<%end%>
Use proper spaces

2021-03-13 13:57 UTC, kalpana19sharma commented on test/fixtures/users.yml
> +# Read about fixtures at https://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html
Remove this file

2021-03-13 13:57 UTC, kalpana19sharma commented on test/models/user_test.rb
> +require "test_helper"
Remove this file

2021-03-15 09:41 UTC, kalpana19sharma commented
@Gupta-Shivanee Please use significant commit names.

2021-03-15 09:53 UTC, kalpana19sharma requested changes

2021-03-15 09:53 UTC, kalpana19sharma commented on app/controllers/sessions_controller.rb
> +    if user&.authenticate(params.require(:password))
Extract strong parameters in a separate method. And permit the parameters.

2021-03-15 09:53 UTC, kalpana19sharma commented on app/controllers/sessions_controller.rb
> +  def welcome; end
This action should not be in sessions controller.

2021-03-15 09:53 UTC, kalpana19sharma commented on app/controllers/users_controller.rb
> +  skip_before_action :authenticate_user!, only: [:new, :create]
Use `%i` syntax for array of symbols

2021-03-15 09:53 UTC, kalpana19sharma commented on app/controllers/users_controller.rb
> +    session[:user_id] = @user.id
What if user is not created?

2021-03-15 09:53 UTC, kalpana19sharma commented on app/controllers/users_controller.rb
> +  def show; end
Where are you using this action?

2021-03-15 09:53 UTC, kalpana19sharma commented on app/views/sessions/welcome.html.erb
> +<%= button_to "Sign Up", new_user_url, method: :get %>
Prefer using `_path` instead of `_url`

2021-03-15 09:53 UTC, kalpana19sharma commented on config/routes.rb
> +  resources :users, only: [:new, :create, :show]
Use `%i` syntax.

2021-03-15 09:53 UTC, kalpana19sharma commented on config/routes.rb
> +  delete 'sessions/:id', to: 'sessions#logout', as: 'logout'
Can we use resources for sessions as well?

2021-03-15 13:42 UTC, Gupta-Shivanee commented on app/controllers/sessions_controller.rb
> +  def welcome; end
ma'am i am using welcome as an index, so ma'am where would i place this action.

2021-03-15 13:47 UTC, Gupta-Shivanee commented on app/controllers/users_controller.rb
> +    session[:user_id] = @user.id
in the next line, i am using if else condition for checking if user created successfully then it will redirect to show page otherwise generate a flash message "Unsuccessful Sign up!".

2021-03-15 13:49 UTC, Gupta-Shivanee commented on config/routes.rb
> +  delete 'sessions/:id', to: 'sessions#logout', as: 'logout'
i have tried using resources for session but getting error in logout.

2021-03-15 15:50 UTC, kalpana19sharma commented on app/controllers/users_controller.rb
> +    session[:user_id] = @user.id
You should set session only if user is successfully created and one more thing `create` will insert record in database then what's the need to call `save` method again?

2021-03-17 04:19 UTC, kalpana19sharma approved these changes

2021-03-17 04:19 UTC, merged