Addtocart Functionality
Gupta-Shivanee/E-commerce pull request #8
Opened 2021-04-04 13:44 UTC by Gupta-Shivanee

Trello Ticket:-  https://trello.com/c/0iLgLJ7J/18-e-commerce-website-add-to-cart-functionality

UI Screenshot
![Screenshot from 2021-04-04 19-10-33](https://user-images.githubusercontent.com/79202689/113510741-d611bc00-9579-11eb-84e4-f4aec7baa6f5.png)
![Screenshot from 2021-04-04 19-10-37](https://user-images.githubusercontent.com/79202689/113510747-de69f700-9579-11eb-9b47-f74abe051b42.png)
![Screenshot from 2021-04-04 19-10-44](https://user-images.githubusercontent.com/79202689/113510749-e033ba80-9579-11eb-908d-b4b06d084091.png)

2021-04-05 06:40 UTC, kalpana19sharma commented
@Gupta-Shivanee please resolve the conflicts

2021-04-05 07:30 UTC, kalpana19sharma commented
Still not resolved. Try not to force push.

2021-04-05 07:36 UTC, Gupta-Shivanee commented
> Still not resolved. Try not to force push.

ma'am here it is showing this branch has no conflict.

2021-04-05 07:43 UTC, kalpana19sharma requested changes

2021-04-05 07:43 UTC, kalpana19sharma commented on app/controllers/application_controller.rb
> +      if session[:cart_id]
What's the need to use `session` here? Also I think you can utilize model callbacks to make this code less complex.

2021-04-05 07:43 UTC, kalpana19sharma commented on app/controllers/cart_items_controller.rb
> +    redirect_to products_path
Set success message.

2021-04-05 07:43 UTC, kalpana19sharma commented on app/controllers/cart_items_controller.rb
> +    @cart_item = CartItem.find_by_id(cart_item_id_params[:id])
Use association.

2021-04-05 07:43 UTC, kalpana19sharma commented on app/models/cart.rb
> +  end
Is there any other more efficient way to do this?

2021-04-05 07:43 UTC, kalpana19sharma commented on app/models/cart_item.rb
> +    self.quantity * self.product.price
```suggestion
    quantity * product.price
```

2021-04-05 10:01 UTC, kalpana19sharma requested changes

2021-04-05 10:01 UTC, kalpana19sharma commented on app/controllers/application_controller.rb
> +    @current_cart = Cart.create
You can use after create callback in use model to create cart so that you don't need to check here for every request.

2021-04-05 10:01 UTC, kalpana19sharma commented on app/controllers/application_controller.rb
> +    session[:cart_id] = @current_cart.id
What's the need to keep cart id in session?

2021-04-05 10:01 UTC, kalpana19sharma commented on app/models/cart.rb
> +    cart_items.to_a.sum { |item| item.total_price }
```suggestion
    cart_items.sum(&:total_price)
```
Test it properly

2021-04-06 10:39 UTC, kalpana19sharma requested changes

2021-04-06 10:39 UTC, kalpana19sharma commented on app/controllers/carts_controller.rb
> +    @cart_items = @cart
whats the need for this?

2021-04-06 10:39 UTC, kalpana19sharma commented on app/views/carts/index.html.erb
> +<% @cart_items.cart_items.each do |cart_item| %>
Don't you think it should be `@cart.cart_items` or `@cart_items`?

2021-04-06 10:53 UTC, kalpana19sharma approved these changes

2021-04-06 10:53 UTC, merged