Placeorder
Gupta-Shivanee/E-commerce pull request #9
Opened 2021-04-06 11:48 UTC by Gupta-Shivanee

Trello Ticket:- https://trello.com/c/4W2DirvJ/19-e-commerce-website-place-order

UI Screenshot-

![Screenshot from 2021-04-06 17-10-39](https://user-images.githubusercontent.com/79202689/113706200-097c5400-96fc-11eb-98ed-7b5fb8f96383.png)
![Screenshot from 2021-04-06 17-10-49](https://user-images.githubusercontent.com/79202689/113706219-0bdeae00-96fc-11eb-86b4-f6c7f2bc71d1.png)
![Screenshot from 2021-04-06 17-13-48](https://user-images.githubusercontent.com/79202689/113706230-0ed99e80-96fc-11eb-874a-363937dc2298.png)
![Screenshot from 2021-04-06 17-13-55](https://user-images.githubusercontent.com/79202689/113706239-113bf880-96fc-11eb-9bfc-3dde64d6418c.png)

2021-04-14 13:56 UTC, kalpana19sharma requested changes

2021-04-14 13:56 UTC, kalpana19sharma commented on app/controllers/orders_controller.rb
> +      product = Product.find_by(id: item.product_id)
Use association

2021-04-14 13:56 UTC, kalpana19sharma commented on app/controllers/orders_controller.rb
> +      @cart.cart_items.each do |item|
Do we really need to run this loop 2 times?

2021-04-14 13:56 UTC, kalpana19sharma commented on app/controllers/orders_controller.rb
> +  private
No need to specify `private` keyword multiple times

2021-04-14 13:56 UTC, kalpana19sharma commented on app/views/orders/index.html.erb
> +    <% order.cart_items.each do |item| %>
Can we use eager loading for removing n+1 database queries?

2021-04-14 13:56 UTC, kalpana19sharma commented on app/views/orders/index.html.erb
> +    <% @address = Address.where(id: order.address_id) %>
Use association

2021-04-14 13:56 UTC, kalpana19sharma commented on app/views/orders/new.html.erb
> +    <% @address = current_user.addresses.all %>
This logic should be controller and variable name should be plural

2021-04-14 13:56 UTC, kalpana19sharma commented on config/routes.rb
> +  resources :orders
Are we using all of the default routes?

2021-04-15 10:36 UTC, Gupta-Shivanee commented on app/controllers/orders_controller.rb
> +      @cart.cart_items.each do |item|
Yes ma'am, in 1st loop we are checking whether required quantity of all the products are available or not, if yes then in 2nd loop we will deduct the actual product quantity in database.

2021-04-19 04:05 UTC, kalpana19sharma approved these changes

2021-04-19 04:06 UTC, kalpana19sharma commented
@Gupta-Shivanee Please resolve the conflicts and `Squash and merge` the PR

2021-04-19 06:21 UTC, merged